### PR TITLE
Added script to extract data from the UWV NOW registry

### PR DESCRIPTION
**Pull request by Sikerdebaard**
UWV has released a list, in pdf format, that contains all the companies that applied for NOW support. This might be interesting to add to this repo.

The ipynb contains the code for downloading the pdf, extracting the table data and converting it to csv. Currently UWV has only released this one pdf, but they seem to plan on releasing this data on a somewhat regular basis in the near future.

For more information on this dataset please have a look at [the uwv website](https://www.uwv.nl/overuwv/pers/documenten/2020/gegevens-ontvangers-now-1-0-regeling.aspx).

### CODE REVIEW

**Comment by J535D165** [comment]
Thanks! Interesting dataset. 

It might not be completely the scope of this repo, however, I really like the dataset. 2048 pages wauw. Can you output the data to the `data-misc` folder? I'm not sure whether I'm interested in the raw data. This will blow up the repo one day ;)

**Comment by Sikerdebaard** [comment]
Done. Removed the pdf as well. I'll monitor for new releases by uwv manually once in a while.

**Comment by Sikerdebaard** [comment]
@J535D165 Any plans to merge this? :)

**Comment by J535D165** [comment]
Check. Thanks a lot. I will spend some time on proper metadata on this dataset.

**Pull request merged**
