### PR TITLE
Readme in nl

### PR DESCRIPTION
**Pull request by SebastiaanBekker**
Hallo,

Mooi project! En zag dat jullie een NL readme zochten. Helpt dit? Laat maar weten als je wat anders wil of zoekt. ZAl ook nog naar de andere issues kijken.

### CODE REVIEW

**Comment by SebastiaanBekker** [comment]
@J535D165 de check failt, waarschijnlijk op de provinciekaart. Zover ik kan zien niet door mijn change, kan ik verder nog wat doen?

**Comment by SebastiaanBekker** [comment]
https://github.com/J535D165/CoronaWatchNL/issues/11 probably linked to this one?

**Comment by SebastiaanBekker** [comment]
@J535D165 lijkt nu te werken....

**Comment by J535D165** [comment]
Great contribution. Let me have a final check tomorrow. I'm thinking about the duplicated plots and what to do about this. 

Looking forward to merge

**Comment by SebastiaanBekker** [comment]
Good one, we can also link to a separate English.md, dutch.md in the readme. Happy to set it up. @J535D165 just let me know. Have some time tonight.

**Comment by SebastiaanBekker** [comment]
@J535D165 Would this work? We're making it more complex, as changes need to be on both .md files, but would work for now.

**Comment by SebastiaanBekker** [comment]
But also happy to set up differently, this was 5 mins copy/paste

**Comment by vmenger** [comment]
FYI, #36 moved some of the graphs into subpages in the /readmes dir. I did not make any changes to content, but I did copy/paste the message at the start of the "Graphs" section into the separate subpages. I also added three links to the subpages in the main readme file.

**Comment by SebastiaanBekker** [comment]
Do you want me to revert the last change?

**Pull request merged**
