### PR TITLE
explain sigmoidal fit in README

### PR DESCRIPTION
**Pull request by japhir**
this seems to have re-included all my previous commits somehow?

### CODE REVIEW

**Comment by J535D165** [comment]
Oke, keep me posted!

**Comment by japhir** [comment]
The changes to the README would be worth merging imo, they try to explain the sigmoidal fit and link to the video.

**Comment by J535D165** [comment]
True, I can't merge a part of your PR. Would you like to make a separate PR or can I make a commit myself (Then this commit doesn't count towards you contributing  statistics). 

Really like your additions to the README

**Comment by japhir** [comment]
What are the actual conflicts? Because while it does some extra calculations in plot.R the figures are the same except that it makes a new one. So they could be merged as well but would run a tiny bit of extra code that is currently not used. Otherwise I can try to figure out how to uncommit those changes.

**Comment by japhir** [comment]
Oh and I think adding the log plot with the exponential fit would be good, because it illustrates how well the data fit the exponential fit

**Comment by J535D165** [comment]
Thanks, did a manual merge. Not sure whether all mutations to plots.R are there. Readme was update. Nice to have this info 

Next time, please do not use master for making changes and update with upstream: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Pull request closed without merging**
