### PR TITLE
quite drastic plot revisions

### PR DESCRIPTION
**Pull request by japhir**
- add 'measures' data to annotate measures taken by the government so far (manually)
- annotate the measures with a geom_rug, geom_rect, and geom_text (overkill?)
- annotate "today" with a vertical red line and the date
- rewrite plot titles to be more accurate (and slightly less flashy). Understandable?
- refactor date labeller code and xlim/ylim into coord_cartesian

adresses #28

### CODE REVIEW

**Comment by J535D165** [comment]
Very promising. Will have a look tomorrow morning!

**Comment by japhir** [comment]
This should probably be discussed before merging, since there are quite some changes that are personal preference as well. Or maybe I should've pushed the addition of the measures separately from the other plot revisions.

**Comment by japhir** [comment]
With 3c8b11e, I fit the exponential to only the >200 cases points and now the predictions are a bit better. I did this because in the log10 plot it looked like things were behaving more exponentially in the latter part, and the data are very susceptible to noise on the few cases side of the line.

**Comment by japhir** [comment]
6c61be6 fixes #11 locally for me, maybe it now also works in the pipe?

**Comment by japhir** [comment]
Oh crap, looks like I made the titles too long to fit on the plots. Will update tomorrow!

**Comment by J535D165** [comment]
Really looking forward to merge this one. Looks great!

**Comment by japhir** [comment]
Should be okay now! You can check out what I did to the plots on [my branch](https://github.com/japhir/CoronaWatchNL/tree/pimpplots), not in the individual commit diffs.

**Comment by J535D165** [comment]
Thanks!!! I really like the improvements. 

Can we make labels A, B, C, D for example for the countermeasures? Really like them, but they are hard to read. 

And bit wondering what to think about the 'today' line. This is always the end of the graph isn't it?

**Comment by J535D165** [comment]
It might be a good idea to keep the original trend graph as well as the one with the events.

**Comment by japhir** [comment]
I've removed the today line and simplified the events annotation. It may be cool to add a little footer with "Plot gemaakt op: <date>, zie github.com/CoronaWatchNL" or something to each plot?

**Comment by japhir** [comment]
Oh yeah, even though I've pulled your master and updated I think I haven't merged it with my pimpplots branch, so all my plots are outdated. Which is kinda cool 'cause we can check the previous predictions based on our super simple models :).

**Comment by J535D165** [comment]
Cool, nice changes. I do have some time tomorrow to merge this.

> It may be cool to add a little footer with "Plot gemaakt op: , zie github.com/CoronaWatchNL" or something to each plot?

Sounds good. I did something similar in the gifs. It should be doable. But let's merge this one first.

**Comment by J535D165** [comment]
I'm no longer auto-updating the plots. Too many problems and I don't have time to fix them.

**Comment by japhir** [comment]
Very nice work @vmenger :).

I think this time I managed to fetch and merge master before committing my new changes, so this should be a bit easier to merge.

I've added the hospitalisation and fatality data to the first plot #31 and did some refactoring.

**Comment by J535D165** [comment]
Love this plot: https://github.com/J535D165/CoronaWatchNL/raw/master/plots/timeline.png

**Comment by vmenger** [comment]
Cool stuff! @japhir

**Pull request merged**
