### PR TITLE
Tabular data extraction proposal for RIVM pdf reports

### PR DESCRIPTION
**Pull request by Sikerdebaard**
I'd like to propose a method for extracting tabular data from the RIVM pdf reports.

The flow is as follows:
- Extract the report pdf from the RIVM website
- Extract text from the pdf using pdftotext package
- Search for a page with the text 'Virologische dagstaten'
- Extract the table on this page using tabula package
- Clean up and filter the data
- Convert to pandas DataFrame

### CODE REVIEW

**Comment by J535D165** [comment]
I really like this one. I do have a script to parse the pdf reports, which is based on regular expressions. This fails pretty often. This approach looks way more stable. I will integrate your PR in our workflow. 

The main research why I skipped 'Virologische dagstaten' in the last reports was because of the new format. We have to work on a new dataset to store them.

**Comment by Sikerdebaard** [comment]
What objections are there against summing the 'Virologische dagstaten' to get the cumulative number as in the current dataset?

I'm kind of motivated to help out in fixing this as the charts on [covid-analytics](https://covid-analytics.nl/population.html#chart-tests-done-vs-positive) are starting to lag behind.

For me it doesn't matter if it's a daily or a cumulative number. One can be derived from the other anyway.

**Comment by Sikerdebaard** [comment]
I've updated the script. It now uses text-extraction and some regex only.

After testing the above method on all pdf's in the reports folder it proved rather unreliable. The text extraction + regex method currently seems the most stable.

The script is a bit of a mess, but it only needs to work until RIVM releases the data on statline anyways.

Now please don't merge this yet because this scripts output format for ```data/rivm_NL_covid19_tests.csv``` is different from the original. In the original all datapoints for all release dates are stored, while the version from this script only keeps the most recent one. My reason for doing this is that we could perhaps split up the format: one file with the most up-to-date values and one that also contains historical data.

Let me know what you prefer.

**Comment by J535D165** [comment]
Thanks! Let's see what happens this week https://github.com/J535D165/CoronaWatchNL/issues/58#issuecomment-621429729. Hopefully, this solves the problem with the test dataset.

**Comment by J535D165** [comment]
Hi @Sikerdebaard, thanks for this PR. 

We had a close look at the data and the changes over the past week. We came to the conclusion that there is no safe way to update the old dataset with the new format of the reports. We don't think there is a safe way to combine the cumulative numbers with the weekly numbers because the weekly numbers have a different starting date. 

We decided to create a new dataset and keep the old for reference. The new structure is also slightly different: https://github.com/J535D165/CoronaWatchNL/tree/master/data-misc#test. Does this work for you? 

I'm thinking about merging parts of your script into the repo because they are very useful.  I had never thought about the workflow with finding the relevant page in the pdf as you do. This is very useful for the other workflows as well. Another thing, I'm working on reactivating the Zenodo integration. You're working as a Ph.D. student. May I add you as a contributor? If you like, can you provide me your ORCID?

**Comment by Sikerdebaard** [comment]
You can do whatever you want with this script.

I'm not familiar with Zenodo / ORCID. I'll look into it.

The new format looks nice.

**Pull request closed without merging**
