### PR TITLE
updated lcps parser

### PR DESCRIPTION
**Pull request by Sikerdebaard**
It looks like the lcps json hasn't been updated for quite some time now. Upon closer inspection of the javascript at lcps.nu it seems they have switched to a different system as no json is retrieved anymore. Because of this the next best option seems to be to scrape the website.

I've updated the script to use beautifulsoup to scrape https://lcps.nu/nieuws/. This script almost works, but seems to generate duplicate rows in the output csv. I'm not sure why this happens and I'm running out of time so perhaps someone else has time to have a look at this issue?

### CODE REVIEW

**Comment by J535D165** [comment]
Very nice!

**Comment by J535D165** [comment]
Works like a charm. Added todays data.

**Comment by wbijster** [comment]
@Sikerdebaard Many thanks! Just one question: what is "title = titlenormalizer(item['title'])"? I understand that you get the value out of the title but where does titlenormalizer come from?

**Comment by Sikerdebaard** [comment]
I'm not familiar with the parse module, it looks like this could potentially be used to do the same as titlenormalizer and titleclassifier combined, but in a more pythonic and probably more compact way.

For the moment, titlenormalizer prepares the title string so that it can be parsed by the titleclassifier. The output of which is used to decide if this news item contains numbers that we are interested in or if it contains something else. If it contains something else, the message is ignored.

**Comment by J535D165** [comment]
I had to make an emergency fix yesterday. One file was completely blown up with duplicate records. 

Main reason: incorrect dates in July resulted in amplification of duplicates. 

We are now taking the last 10 news items into account. 

image

**Comment by Sikerdebaard** [comment]
Ah great catch! I've notified someone at lcps about this error, let's see if they fix it. I'd like to know what the real number is for that date and what date the other number belongs to, or if they simply just published twice on that day. Hopefully they reply. :)

**Comment by J535D165** [comment]
I had a look at our git file history. 

```
lcps website - correction
14 juli - 14 juli
16 juli - 15 juli
17 juli - 16 juli
17 juli - 17 juli
18 juli - 18 juli
20 juli - 19 juli
20 juli - 20 juli
21 juli - 21 juli
```

15 is missing, 17 and 20 are duplicated. The order is correct.

**Comment by wbijster** [comment]
FYI this is what I have from my daily manually checked collection of data, it is shared as [Excel worksheet](https://service.openinfo.nl/downloads/corona-cijfers-per-dag-op-gemeente-provincie-en-landelijk-niveau/) as well.

`Datum,IC-bezetting totaal,IC-bezetting Corona,Ziekenhuis opnames Corona buiten de IC
2020-08-04,590,26,83
2020-08-06,627,29,79
2020-08-07,591,27,78
2020-08-08,604,28,79
2020-08-09,576,31,87
2020-08-10,600,29,99
2020-08-11,613,30,97
2020-08-12,648,35,115
2020-08-13,643,31,127
2020-08-14,616,38,120
2020-08-15,622,39,124
2020-08-16,614,36,122
2020-08-17,604,39,126
2020-08-18,646,42,129
2020-08-19,649,41,125
2020-08-20,633,39,138
2020-08-21,646,43,133
2020-08-22,633,42,131
2020-08-23,607,42,129
2020-08-24,593,41,121
2020-08-25,639,38,120
2020-08-26,660,38,120
2020-08-27,649,36,107
2020-08-28,641,34,100
2020-08-29,611,34,96
2020-08-30,591,33,94
2020-08-31,588,38,94
2020-09-01,622,33,93
2020-09-02,649,32,90
2020-09-03,620,28,95
2020-09-04,639,35,95
2020-09-05,632,35,99
2020-09-06,609,33,105
2020-09-07,583,31,109
2020-09-08,662,30,116
2020-09-09,647,31,122`

**Pull request merged**
