### PR TITLE
Add plots per region and plots for hospitalisation.

### PR DESCRIPTION
**Pull request by jpvandervelden**
Add plots per region and plots for hospitalisation.

### CODE REVIEW

**Comment by japhir** [comment]
I can't see the plots by the way, did you exclude them from the commits on purpose? So that when it's committed the autorun should add them? Will the autorun be able to add new files @J535D165?

**Comment by jpvandervelden** [comment]
I was asked to leave the plots out.

Op do 2 apr. 2020 17:17 schreef Ilja Kocken <notifications@github.com>:

**Comment by jpvandervelden** [comment]
BTW the python plots build step shows up green but it's actually failing in the following way:
Traceback (most recent call last):
  File "plot_scripts/animated_maps.py", line 7, in <module>
    import geopandas  # requires descartes
ModuleNotFoundError: No module named 'geopandas'
This is the first step in plots.sh. animated_maps.py wasn't touched by my changes...

**Comment by J535D165** [comment]
Thanks @jpvandervelden, thanks @japhir. Yes, thanks for the code. I will render the plots to prevent all kinds of merge conflicts. The automated workflow is broken (known issue). 

Happy to merge!

**Comment by jpvandervelden** [comment]
Thanks!

Op do 2 apr. 2020 20:21 schreef Jonathan de Bruin <notifications@github.com

**Comment by J535D165** [comment]
The plots have been added. Really nice contribution. https://github.com/J535D165/CoronaWatchNL/blob/master/readmes/forecast_plots.md

@vmenger Have you seen them?

**Pull request merged**
